name: Deploy Digital Garden

on:
  push:
    branches: [ "main" ]

# Даем воркфлоу права на публикацию в GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build --if-present

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist' # Указываем папку, куда Eleventy собирает готовый HTML

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
